<Project>
  <PropertyGroup>
    <MauiVersion Condition="'$(MauiVersion)' == ''">8.0.100</MauiVersion>
    <CheckEolTargetFramework Condition="'$(CheckEolTargetFramework)' == ''">false</CheckEolTargetFramework>
    <CheckEolWorkloads Condition="'$(CheckEolWorkloads)' == ''">false</CheckEolWorkloads>
  </PropertyGroup>
</Project>
